/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    food_lime_01: THREE.Mesh;
  };
  materials: {
    food_lime_01: THREE.MeshStandardMaterial;
  };
};

export default function Lime({ ...props }: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/lime/food_lime_01_4k.gltf"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null} scale={30}>
      <mesh
        geometry={nodes.food_lime_01.geometry}
        material={materials.food_lime_01}
      />
    </group>
  );
}

useGLTF.preload("/lime/food_lime_01_4k.gltf");
